### ISSUE TITLE
Support workflow presets

### ISSUE THREAD

**Issue by quyykk** [lukka/run-cmake#102]
CMake 3.25 adds a new preset, the [workflow preset](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#workflow-preset), which is very useful in CI because it describes an arbitrary sequence of build and test (and package) presets.

Thanks!

**Comment by lukka** [comment]
@quyykk how do you think this should work for `run-cmake`? 
1. One way would be to add a new input called `workflowPreset`, a string, which when it's set, the action runs `cmake --workflow --preset <name>`. 
2. When `workflowPreset` is set, the `buildPreset` and `configurePreset` inputs are disregarded (with a warning message).
3. Is a `workflowPresetAdditionalArgs` input useful? 

Any input is appreciated, thanks!

**Comment by quyykk** [comment]
> One way would be to add a new input called `workflowPreset`, a string, which when it's set, the action runs `cmake --workflow --preset <name>`.

yeah. Does it makes sense to pass `--fresh` as well (it cleans any build files)?

> When `workflowPreset` is set, the `buildPreset` and `configurePreset` inputs are disregarded (with a warning message).

makes sense

> Is a `workflowPresetAdditionalArgs` input useful?

The only potential argument to pass is `--fresh`, so probably not?

**Comment by lukka** [comment]
@quyykk solved in https://github.com/lukka/run-cmake/releases/tag/v10.3, let me know if this works for you!
