### ISSUE TITLE
Support package presets

### ISSUE THREAD

**Issue by malaterre** [lukka/run-cmake#107]
In issue #102 workflow preset support was added, but not package preset. Could you please add "packagePreset" support just like `configurePreset/buildPreset`.

ref:
* https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#package-preset

thanks !

**Comment by lukka** [comment]
@malaterre good idea! Would you be able to provide a small sample of how it would be used? I need to add a sample like the workflow one: https://github.com/lukka/CppBuildTasks-Validation/blob/v10/.github/workflows/hosted-cmake-workflow.yml
I haven't done my homework yet, and have these questions:
- Is it mutually exclusive as the `workflow` preset? 
- Or it can go along with any of the configure/build/test presets? 
- Is the preset an argument to `cpack` or to `cmake`?

**Comment by lukka** [comment]
@malaterre ok, go it. Would you mind testing this version suits your needs?
`lukka/run-cmake@dev/package-preset`

**Comment by lukka** [comment]
@malaterre thanks for trying, I fixed it, you may try again.

**Comment by lukka** [comment]
Solved in #109
