### ISSUE TITLE
Build output not visible during/after build when using a build preset

### ISSUE THREAD

**Issue by vadi2** [lukka/run-cmake#112]
The build output is not visible when using a build preset:

[Screen recording 2023-05-14 3.34.25 PM.webm](https://github.com/lukka/run-cmake/assets/110988/2476d43c-32d5-4016-a915-bdfa81a29d6d)

Looking at the raw logs, it seems to be hidden inside the configure step.

This is not an issue when build presets aren't involved:

![image](https://github.com/lukka/run-cmake/assets/110988/56cfde02-c53c-4bcb-8ff5-16fd2da31aaa)

**Comment by vadi2** [comment]
It's the same after a build is completed:

![image](https://github.com/lukka/run-cmake/assets/110988/81d3f905-b273-4a5d-9c54-94f7ed072b4c)

**Comment by lukka** [comment]
@vadi2 thanks for the report! Could you please provide a link to a workflow run where this happened? Also, it may be that you still have enabled the option `--debug-find` that probably is too verbose.

**Comment by vadi2** [comment]
It's the workflow in https://github.com/Mudlet/Mudlet/pull/6772. Totally did have `--debug-find` enabled, thanks for that.

**Comment by lukka** [comment]
@vadi2 let me know if this is still an existing problem, closing this issue for now.
