### ISSUE TITLE
Add support for build cache

### ISSUE THREAD

**Issue by magnesj** [lukka/run-cmake#13]
Hi,

I am looking into how to use a build cache to reduce build times. Is this something you might consider to include in your GitHub Action?

One alternative that looks promising https://github.com/mbitsnbites/buildcache

Regards
Magne

**Comment by lukka** [comment]
I took a brief look to the buildcache tool, look interesting. Regarding run-cmake, I think you can use it in one of these ways:

1. [instruct CMake to run buildcache in place of the compiler](https://github.com/mbitsnbites/buildcache/blob/master/doc/usage.md#using-with-cmake);
1. create a toolchain for using buildcache in CMake;
1. use the [cmakeWrapperCommand](https://github.com/lukka/run-cmake/blob/v1/action.yml#L77) input, it allows you to run CMake onto the environment set up by a  wrapper for buildcache.

Is there anything in particular feature that you have in mind that may be good to have?

**Comment by magnesj** [comment]
Thanks for you comments.

I think it could be useful to have the buildcache as an optional part of run-cmake, and I think your option number 1 is the best and maybe easiest to implement and use.

**Comment by lukka** [comment]
@magnesj if feel like the usage of option number 1 is indeed the most widely used and accepted solution. Avoiding adding another input argument to 'run-cmake' action is also always the best option :)
