### ISSUE TITLE
warning message not highlighted when run with cmake workflows

### ISSUE THREAD

**Issue by RTUnreal** [lukka/run-cmake#143]
Hello,
I have been using this action with the workflow option to run some tests for our project and I noticed a warning was not highlighted in the logs:

https://github.com/RTUnreal/OpenVR-AdvancedSettings/actions/runs/9735208658/job/26864160982#step:8:263

Thank you

**Comment by lukka** [comment]
Fix in https://github.com/lukka/run-cmake/pull/144
@RTUnreal could you test the fix with `run-cmake@dev/fix143` ? Thanks!

**Comment by RTUnreal** [comment]
seems to work
with stable v10:
https://github.com/RTUnreal/OpenVR-AdvancedSettings/actions/runs/9907242249/job/27370491252#step:8:242
with pinned commit:
https://github.com/RTUnreal/OpenVR-AdvancedSettings/actions/runs/9907323632/job/27370758674#step:8:242

**Comment by lukka** [comment]
@RTUnreal fixed in [run-cmake@v10.8](https://github.com/lukka/run-cmake/releases/tag/v10.8). Let me know, thank you!
