### ISSUE TITLE
'env' printed in Windows builds

### ISSUE THREAD

**Issue by vadi2** [lukka/run-cmake#34]
It seems that when using the action on Windows, `env` is printed: https://github.com/Mudlet/Mudlet/runs/1385861365?check_suite_focus=true

![Selection_434](https://user-images.githubusercontent.com/110988/98833706-a503e400-243e-11eb-8b00-f9febddf9d26.png)

This does not happen under macOS or Linux. Perhaps not intended?

**Comment by lukka** [comment]
@vadi2 right, the output should be at least under an expandable section, as it may be annoying. 
As you correctly pointed out, it happens only on Windows when `msvc` is being used (it setups appropriately the Developer Command prompt using the `vcpkg` triplet).

I think it makes sense to put this verbose output under a collapsible log element indeed.

**Comment by vadi2** [comment]
In my case I'm using MinGW, not msvc - from the same link:

![Selection_435](https://user-images.githubusercontent.com/110988/98836963-a800d380-2442-11eb-9714-75a05f9d5beb.png)

But I think that's a minor detail.

**Comment by lukka** [comment]
fixed in [run-cmake@v3](https://github.com/lukka/run-cmake/releases/tag/v3.2)
