### ISSUE TITLE
CMakeSettings.json workflow

### ISSUE THREAD

**Issue by orion160** [lukka/run-cmake#38]
How it is supposed to write a CMakeSettings.json to make the configurations of the build. My actual build is working, but it is because run-cmake is choosing a default config to use in linux.

Linux build for Visual Studio requires a remote machine, so what information run-cmake recollects from that cmake settings schema for Visual Studio?

**Comment by lukka** [comment]
@orion160 CMakeSettings.json content is used to create command line argument to run the CMake configuration and generation and to run the build. 
For remote configuration stored in `CMakeSettings.json`, the `remoteMachineName` or the copy with `rsync` related values are always disregarded, and the build executes always locally.
You may find lot of examples in the [samples](https://github.com/lukka/run-cmake#samples).
