### ISSUE TITLE
How to configure only?

### ISSUE THREAD

**Issue by vadi2** [lukka/run-cmake#43]
I'd like to use the action to generate compile commands - and not run the whole compile process. How can I do that with this action, which'll help cmake take into account all of the dependencies?

**Comment by lukka** [comment]
@vadi2 if you'd like to use CMake to only generate the project files in the build directory (and skip building), you can set the input [buildWithCMake](https://github.com/lukka/run-cmake/blob/main/action.yml#L81) to `false`. By default, it is `true`.

**Comment by vadi2** [comment]
That makes sense. I forgot one can check `action.yml` and just scanned the readme.

**Comment by tobylane** [comment]
Is this still possible? buildWithCMake is gone.

**Comment by lukka** [comment]
@tobylane yes, take a look to the [flowchart](https://github.com/lukka/run-cmake?tab=readme-ov-file#flowchart): only the presets you set will be run, anything that is not provided is skipped. In your case, provide the `configurePreset` only, and it will just configure. Note: it is a must to use CMakePresets.json in v10 onward.
