### ISSUE TITLE
Environment vars in command-line

### ISSUE THREAD

**Issue by rickomax** [lukka/run-cmake#5]
Hi!

I'm not sure if this issue is related to the action itself, but when I try to use an environment var on the CMAKE arguments, it's not recognized.

I've tested setting the -DCMAKE_TOOLCHAIN_FILE using the ANDROID_SDK_ROOT environment variable in two ways, but no one have worked:

Just to clarify, I've already ensured the given toolchain file is on the runner image.

[https://github.com/rickomax/assimp/runs/479700678?check_suite_focus=true](https://github.com/rickomax/assimp/runs/479700678?check_suite_focus=true)
[https://github.com/rickomax/assimp/runs/479685226?check_suite_focus=true](https://github.com/rickomax/assimp/runs/479685226?check_suite_focus=true)

**Comment by rickomax** [comment]
Setting the path manually without the ${ANDROID_SDK_ROOT} environment var on the arguments works. Strange...

**Comment by lukka** [comment]
@rickomax using this in the yml file should work:

`${{ env.ANDROID_SDK_ROOT }}`

You could also use the env variable using a syntax that the OS understand, but would have a different syntax per platform)

**Comment by rickomax** [comment]
Oh, gonna try. Ty!

**Comment by rickomax** [comment]
https://github.com/rickomax/assimp/runs/481149007?check_suite_focus=true

**Comment by lukka** [comment]
From the log, it looks like the ANDROID_SDK_ROOT variable is not set in the environment, as it is empty, as in it has been evaluated to not being set.

` -DCMAKE_TOOLCHAIN_FILE=/ndk-bundle/build/cmake/android.toolchain.cmake`

I can see the evalution done by enabling verbose output on steps/actions, that is:

https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#step-debug-logs

**Comment by rickomax** [comment]
I wonder how it's not set, if I can list it using the "run" action with bash....

**Comment by lukka** [comment]
- run: echo $ANDROID_SDK_ROOT
 - run: echo $ANDROID_HOME

**Comment by rickomax** [comment]
Yeah, it shows values for me

**Comment by lukka** [comment]
ok, can you enable step-debug-log as suggested and run the workflow again?

**Comment by lukka** [comment]
@rickomax i've investigate this further, and indeed the core.exec functions provided by actions/toolkit is not using a shell when launching commands. It looks like a solution would be to contribute back to actions/toolkit to add this functionality, or just do the logic in this action and use 'bash'/'cmd' according to platform and user preferences.

**Comment by lukka** [comment]
Running processes under the platform default shell helps indeed in being able to access to env var.  With [v1 release](https://github.com/lukka/run-cmake/releases/tag/v1.0) you can use env var on the `inputs` of the action.
