### ISSUE TITLE
Update to cmake 3.17.10

### ISSUE THREAD

**Issue by vadi2** [lukka/run-cmake#7]
Not that this action is particularly oudated, but the latest release adds a `–debug-find` flag which is terribly useful in an environment like github actions when you're trying to figure out why is library detection failing.

**Comment by lukka** [comment]
@vadi2 The `run-cmake` action runs the version available on the path environment variable of the runner. Do you think it should provision the runner's machine with the most recent version of cmake?

**Comment by vadi2** [comment]
I didn't realise that was the case. I think that would help, yeah.

In my case I didn't realise there were 2 workspaces, a github and a runner one. In the end I had to modify my cmake file to print the prefix path whereas the new flag would have helped speed that up.

**Comment by lukka** [comment]
@vadi2 ok, makese sense. Keeping this issue open until we get `cmake` version selection and automatic provisioning on the runner's machine.

**Comment by vadi2** [comment]
For anyone else looking into this, the action does use cmake 3.17 now because Github has updated: https://github.com/actions/virtual-environments/commit/4348e23367d47b705d6661f9aae252a4e17374e2

**Comment by lukka** [comment]
@vadi2 I created an ad-hoc action to [install latest cmake in one liner.](https://github.com/marketplace/actions/get-cmake). It is also cached, so next time you save download/extraction, but the binaries are just restored from GitHub's cache. It works on any type of runner, selfhosted or GitHub hosted.

**Comment by vadi2** [comment]
Very nice! Super simple. It's also the latest cmake, isn't it? The page doesn't mention much about it.

**Comment by lukka** [comment]
@vadi2  right, that is missing, it just says 'latest CMake' but it says nothing about which version it is :)
