### ISSUE TITLE
CTest failing on Windows due to no support for RPATH

### ISSUE THREAD

**Issue by davidebeatrici** [lukka/run-cmake#76]
Tests fail to launch with error `0xc0000135` (`STATUS_DLL_NOT_FOUND`) if they depend on a DLL that is built in a different directory by the CMake project.

Can I specify the working directory for CTest?

**Comment by lukka** [comment]
@davidebeatrici This could be helpful: https://stackoverflow.com/questions/43981966/cmake-how-to-specify-directory-where-ctest-should-look-for-executables

**Comment by davidebeatrici** [comment]
Yes, thanks!

It would be great if the working directory could be specified for this action as well.

**Comment by lukka** [comment]
@davidebeatrici i'd be glad if you could explain the feature request more in detail. Note that the action does not invoke `ctest` and all the action can do is to set a working directory when spawning the `cmake` process, if that would be useful.

**Comment by davidebeatrici** [comment]
Switching directory works, as long as the path to the project is specified right after.

I'm not sure whether CTest retains the working directory though.

**Comment by lukka** [comment]
Closing as more than one year of inactivity. Feel free to ask to reopen if needed.
