### ISSUE TITLE
Invalid cache gets saved and never overwritten if project generation fails

### ISSUE THREAD

**Issue by quyykk** [lukka/run-cmake#83]
If the project generation fails for any reason (error in CMakeLists, manually cancelling the workflows, etc.), then the run-vcpkg action saves its cache. However, that cache might be incomplete. Subsequent runs of the workflow use that incomplete cache and if they succeed never update it with actual correct  and complete cache.

I'm not very knowledgeable when it comes to caches, but it seems like it would be possible save caches when run-cmake fails under a different (restore) cache key.

Thanks!

**Comment by lukka** [comment]
@quyykk that is indeed a limitation of how things are implemented in `run-vcpkg` action, contributions are welcome. 

There is already the following issue that is suggesting a workaround and collecting ideas on how to potentially solve the "partial cache saved" problem:  (https://github.com/lukka/run-vcpkg/issues/128)

Closing this issue as this problem pertains to `run-vcpkg` and not to `run-cmake`.
