### ISSUE TITLE
Expand-Archive : is not a supported archive file format.

### ISSUE THREAD

**Issue by KironBikash** [lukka/run-cmake#97]
I am getting this error while trying to make a cmake update action. How can I get rid of it? in my YAML file I am using the following configurations. Thank you in advance.

> env:
>   CONFIGURATION: Debug
> jobs:
>   Build:
>     runs-on: [ self-hosted, Windows, Build ]
>     timeout-minutes: 30
>     strategy:
>       matrix:
>         TARGET: [ 'Windows' ]
>         MSVC_TOOLSET_VERSION:
>           - 14.00
>           - 14.16
>           - 14.29
>           - 14.30
>           - 14.31
>           - 14.32
> steps:
>       - uses: actions/checkout@v3.1.0
>       - uses: ilammy/msvc-dev-cmd@v1.12.0
>         with:
>           arch: x64
>           toolset: $ {{ matrix.MSVC_TOOLSET_VERSION }}
>       - uses: lukka/get-cmake@v3.23.0
>       - uses: lukka/run-cmake@v10.0
>         with:
>           configurePreset: $ {{ matrix.TARGET }}-${{ env.CONFIGURATION }}
>           buildPreset: $ {{ matrix.TARGET }}-${{ env.CONFIGURATION }}

Error:  
        
> C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\actions-runner\_work\_temp\834f221e-b5a4-418c-aa96-71d4f1cbe900' -DestinationPath 'C:\actions-runner\_work\_temp\-1001380349' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\actions-runner\_work\_temp\834f221e-b5a4-418c-aa96-71d4f1cbe900', 'C:\actions-runner\_work\_temp\-1001380349', $true) }" 
> 
> [48](https://github.com/Example-Project/actions/runs/3417566719/jobs/5688848789#step:4:50) Expand-Archive : is not a supported archive file format. The only supported archive file format is .zip.
> [49](https://github.com/Example-Project/actions/runs/3417566719/jobs/5688848789#step:4:51) At line:1 char:210 
> [50](https://github.com/Example-Project/actions/runs/3417566719/jobs/5688848789#step:4:52) + ... Ignore)) { Expand-Archive -LiteralPath 'C:\actions-runner\_work\_tem ... 
> [51](https://github.com/Example-Project/actions/runs/3417566719/jobs/5688848789#step:4:53) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
> [52](https://github.com/Example-Project/actions/runs/3417566719/jobs/5688848789#step:4:54)  + CategoryInfo : InvalidArgument: (:String) [Expand-Archive], IOException 
> [53](https://github.com/Example-Project/actions/runs/3417566719/jobs/5688848789#step:4:55)  + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive

**Comment by lukka** [comment]
@KironBikash  could you provide a link to the workflow that is reproducing the problem?

**Comment by lukka** [comment]
@KironBikash let me know if this is still a problem!

**Comment by derekcyruschow-catapult** [comment]
Potentially related to the issue fixed in https://github.com/actions/setup-python/pull/916 when running on self-hosted Windows runners needing the `.zip` part of the filename to be explicitly stated?

**Comment by lukka** [comment]
@derekcyruschow-catapult IIRC this problem was related to `get-cmake`, and it was reported here: https://github.com/lukka/get-cmake/issues/91
and fixed here: https://github.com/lukka/get-cmake/pull/92
